---
- name: Before everything
  hosts: localhost
  roles:
    - { role: before, tags: [always] }

- name: Setup MacBook and debian
  hosts: [macbook, debian]
  roles:
    - { role: whoami, tags: [always] }
    - { role: install, tags: [install, setup, info] }
    - { role: functions, tags: [functions, install, setup, info] }
    - { role: terminal, tags: [terminal, setup, info] }

- name: Setup debian machines
  hosts: [debian]
  roles:
    - { role: install, tags: [debian] }
    - { role: terminal, tags: [debian] }
    - { role: functions, tags: [debian] }
    - { role: nginx, tags: [debian, nginx] }

- name: Setup macbook
  hosts: macbook
  roles:
    - { role: vscode, tags: [vscode, setup, info] }
    - { role: desktop, tags: [desktop, setup, info] }
    - { role: keepalive, tags: [keepalive, functions, setup, info] }
    - { role: rails, tags: [rails, setup, info] }
    - { role: elixir, tags: [elixir, setup, info] }

- name: After everything
  hosts: localhost
  roles:
    - { role: afterwards, tags: [always] }
