---
- name: Before everything
  hosts: localhost
  tags: always
  tasks:
    - name: Get version
      ansible.builtin.command: npm pkg get version
      register: macfair_version

    - name: Get hostname of control machine
      ansible.builtin.command: hostname
      register: hostname

    - name: Print version
      debug: var=macfair_version.stdout

- name: Setup MacBook and debian
  hosts: [macbook, debian]
  roles:
    - { role: whoami, tags: always }
    - { role: install, tags: [install, setup] }
    - { role: aliases, tags: [aliases, install, setup] }
    - { role: terminal, tags: [terminal, setup] }
    - { role: rails, tags: [rails, setup] }
    - { role: vscode, tags: [vscode, setup] }

- name: Setup debian machines
  hosts: [debian]
  roles:
    - { role: install, tags: debian }
    - { role: terminal, tags: debian }
    - { role: aliases, tags: debian }
    - { role: nginx, tags: [debian, nginx] }

- name: Setup macbook
  hosts: macbook
  roles:
    - { role: desktop, tags: [desktop, setup] }
    - { role: elastic, tags: [elastic, setup] }

- name: After everything
  hosts: localhost
  roles:
    - { role: afterwards, tags: always }
