---
- name: Setup MacBook for a rich development environment
  hosts: all
  vars:
    macbook_user: 'picfair'
    ruby_version: '2.6.6'
  roles:
    - geerlingguy.homebrew
    - initialize
    - terminal
    - languages
    - databases
    - webdev
    - caskapps
    - elastic
    - zsh
    - rails
