---
- name: Setup MacBook and debian
  hosts: [macbook, debian]
  roles:
    - { role: whoami, tags: always }
    - { role: install, tags: install }
    - { role: aliases, tags: [aliases, install] }
    - { role: terminal, tags: terminal }
    - { role: rails, tags: rails }
    - { role: vscode, tags: vscode }

- name: Setup debian machines
  hosts: [debian]
  roles:
    - { role: install, tags: debian }
    - { role: terminal, tags: debian }
    - { role: aliases, tags: debian }
    - { role: webserver, tags: [debian, webserver] }

- name: setup macbook
  hosts: macbook
  roles:
    - { role: desktop, tags: desktop }
    - { role: elastic, tags: elastic }

- name: Are we ready?
  hosts: localhost
  roles:
    - { role: checkhost, tags: always }
