---
- name: before everything
  hosts: localhost
  tags: always
  tasks:
    - name: get version
      ansible.builtin.command: npm pkg get version
      register: macfair_version

- name: Setup MacBook and debian
  hosts: [macbook, debian]
  roles:
    - { role: whoami, tags: always }
    - { role: install, tags: [install, setup] }
    - { role: aliases, tags: [aliases, install, setup] }
    - { role: terminal, tags: [terminal, setup] }
    - { role: rails, tags: [rails, setup] }
    - { role: vscode, tags: [vscode, setup] }

- name: Setup debian machines
  hosts: [debian]
  roles:
    - { role: install, tags: debian }
    - { role: terminal, tags: debian }
    - { role: aliases, tags: debian }
    - { role: nginx, tags: [debian, nginx] }

- name: setup macbook
  hosts: macbook
  roles:
    - { role: desktop, tags: [desktop, setup] }
    - { role: elastic, tags: [elastic, setup] }

- name: After everything
  hosts: localhost
  tags: always
  tasks:
    - name: does host file exist?
      stat:
        path: hosts
      register: hosts

    - name: display post install message
      debug:
        msg:
          - 'Host file not set up yet. To set it up run the following'
          - 'make thistarget'
      when: not hosts.stat.exists
