---
- name: Setup MacBook for a rich development environment
  hosts: all
  vars:
    macbook_user: 'picfair'
    ruby_version: '2.6.6'
  roles:
    - { role: geerlingguy.homebrew, tags: initialize }
    - { role: initialize, tags: initialize }
    - { role: terminal, tags: terminal }
    - { role: databases, tags: databases }
    - { role: webdev, tags: webdev }
    - { role: caskapps, tags: caskapps }
    - { role: elastic, tags: elastic }
    - { role: zsh, tags: zsh }
    - { role: rails, tags: rails }
    - { role: fleetnation, tags: fleetnation }
