---
- name: Setup MacBook for a rich development environment
  hosts: all
  roles:
    - { role: whoami, tags: always }
    - { role: initialize, tags: initialize }
    - { role: terminal, tags: terminal }
    - { role: elastic, tags: elastic }
    - { role: rails, tags: rails }
    - { role: vscode, tags: vscode }
    - { role: desktop, tags: desktop }
