---
- name: Upgrade Ubuntu to next LTS
  hosts: debian
  become: true
  tasks:
    - name: Install update-manager-core
      apt:
        name: update-manager-core
        state: present

    - name: Check if upgrade is available
      command: do-release-upgrade -c
      register: upgrade_check
      failed_when: false
      changed_when: false

    - name: Skip if no upgrade available
      meta: end_play
      when: upgrade_check.rc != 0

    - name: Record pre-upgrade state
      shell: |
        echo "=== Podman ===" && podman version 2>/dev/null || true
        echo "=== Volumes ===" && podman volume ls 2>/dev/null || true
        echo "=== Containers ===" && podman ps -a 2>/dev/null || true
        echo "=== Disk ===" && df -h /
      register: pre_state
      changed_when: false
      become_user: "{{ ansible_user }}"

    - name: Show pre-upgrade state
      debug:
        var: pre_state.stdout_lines

    - name: Update all packages before upgrade
      apt:
        update_cache: true
        upgrade: dist

    - name: Check if reboot required after apt upgrade
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required before release upgrade
      reboot:
        reboot_timeout: 300
      when: reboot_required.stat.exists

    - name: Run do-release-upgrade non-interactively
      shell: nohup do-release-upgrade -f DistUpgradeViewNonInteractive </dev/null >/var/log/do-release-upgrade.log 2>&1 &
      async: 0
      poll: 0

    - name: Wait for host to come back after upgrade
      wait_for_connection:
        delay: 60
        timeout: 1800

    - name: Reboot after upgrade
      reboot:
        reboot_timeout: 300

    - name: Verify new release
      command: lsb_release -a
      register: new_release
      changed_when: false

    - name: Show new release
      debug:
        var: new_release.stdout_lines
