---
- name: does host file exist?
  stat:
    path: hosts
  register: hosts

- name: display post install message
  debug:
    msg:
      - 'Host file not set up yet. To set it up run the following:'
      - 'make prepare'
      - Then edit resulting hosts file and hosts_vars/{{ ansible_hostname }}.yml file if necessary
  when: not hosts.stat.exists
