---
- name: install helpful packages
  homebrew:
    name: [
      "nginx",
      "graphviz",
    ]
    state: present

- name: install Node and yarn
  homebrew:
    name: [
      "node@16",
      "yarn",
    ]
    state: present

- name: link node16
  shell: brew link --overwrite node@16

- name: Install vercel, netlify
  npm:
    name:  "{{ item }}"
    global: yes
  with_items:
    - "vercel"
    - "netlify-cli"
    - "railway"
