---
- name: install helpful packages
  homebrew:
    name: [
      "nginx",
      "graphviz",
    ]
    state: present
  tags:
    - webdev

# - name: install python packages
#   homebrew:
#     name: [
#       "pipenv",
#       "pyenv",
#       "pyenv-virtualenv",
#       "pyenv-virtualenvwrapper",
#       "autopep8",
#       "flake8",
#     ]
#     state: present
#   tags:
#     - webdev

- name: install Node and yarn
  homebrew:
    name: [
      "node@14",
      "yarn",
    ]
    state: present
  tags:
    - webdev

- name: link node14
  shell: brew link --overwrite node@14
