- name: Add yay domain to dnsmasq.conf
  lineinfile:
    path: "/opt/homebrew/etc/dnsmasq.conf"
    line:  "address=/.{{ item.domain }}/{{ item.ip }}"
    insertbefore: EOF
  with_items: "{{ local_domains }}"

- name: Find dnsmasq plist file
  ansible.builtin.command: find /opt/homebrew/Cellar -name homebrew.mxcl.dnsmasq.plist
  register: dnsmasq_plist

- name: Print dnsmasq plist file path
  ansible.builtin.debug:
    var: dnsmasq_plist.stdout_lines

- name: Copy the daemon configuration file into place
  ansible.builtin.command: "cp {{dnsmasq_plist.stdout_lines[0] }} /Library/LaunchDaemons/"
  become: true

- name: unload dnsmasq.plist
  ansible.builtin.command: launchctl unload /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
  become: true

- name: load dnsmasq.plist
  ansible.builtin.command: launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
  become: true

- name: empty the dns
  ansible.builtin.command: networksetup -setdnsservers Wi-Fi empty
  become: true

- name: use the dns
  ansible.builtin.command: networksetup -setdnsservers Wi-Fi 127.0.0.1 9.9.9.9
  become: true
