ansible_connection: local
iterm_theme: "coffee"
zsh_theme: "cerico-w-user"

desktop_app_bindings:
  - bundle_id: com.vivaldi.Vivaldi
    desktop: 1
  - bundle_id: org.mozilla.firefox
    desktop: 2
  - bundle_id: com.linear
    desktop: 3
  - bundle_id: com.tinyspeck.slackmacgap
    desktop: 3
  - bundle_id: md.obsidian
    desktop: 4
  - bundle_id: com.ableton.live
    desktop: 15
  - bundle_id: com.apple.finder
    desktop: 16
  - bundle_id: com.apple.Preview
    desktop: 16
  - bundle_id: com.apple.Safari
    desktop: 16
