---
- name: Copy zshrc
  copy:
    src: zshrc
    dest: ~{{ macbook_user.stdout }}/.zshrc

- name: Create zsh directory
  file:
    path: "~{{ macbook_user.stdout }}/.zsh"
    state: directory

- name: Copy aliases
  copy:
    src: zsh/aliases
    dest: ~{{ macbook_user.stdout }}/.zsh/aliases

- name: Copy darwin
  copy:
    src: zsh/darwin
    dest: ~{{ macbook_user.stdout }}/.zsh/darwin

- name: Copy git aliases
  copy:
    src: zsh/git
    dest: ~{{ macbook_user.stdout }}/.zsh/git

- name: Add darwin to path.
  lineinfile:
    path: ~/.zsh/aliases
    line: source ~/.zsh/darwin
    insertbefore: BOF

- name: create empty tokens file only if one doesnt already exist
  copy:
    content: ""
    dest: ~{{ macbook_user.stdout }}/.zsh/tokens
    force: no

- name: create trial file for new aliases if one doesn't already exist
  copy:
    content: "tinker(){\n  echo try out new aliases here, not in main file\n}"
    dest: ~{{ macbook_user.stdout }}/.zsh/trialling
    force: no

- name: copy js help file
  copy:
    src: help.js
    dest: ~{{ macbook_user.stdout }}/.zsh/help.js

- name: Register ansible location
  become: false
  shell: command python3 -m site --user-base
  register: python_location

- name: Add ansible to path.
  lineinfile:
    path: ~/.zshrc
    line: export PATH="{{ python_location.stdout }}/bin:$PATH"

- name: register rbenv exists
  stat:
    path: ~{{ macbook_user.stdout }}/.rbenv/bin/rbenv
  register: rbenv

- name: Conditionally Copy zsh rails
  copy:
    src: zsh/rails
    dest: ~{{ macbook_user.stdout }}/.zsh/rails
  when: rbenv.stat.exists

- name: Conditionally Add rails to zshrc.
  lineinfile:
    path: ~/.zshrc
    line: source $HOME/.zsh/rails
  when: rbenv.stat.exists

- name: import dnsmasq.yml
  import_tasks: dnsmasq.yml
  when: inventory_hostname != 'github-runner.localhost'

- name: Copy dns aliases
  copy:
    src: zsh/dns
    dest: ~{{ macbook_user.stdout }}/.zsh/dns

- name: Makes zsh the cron shell
  ansible.builtin.cron:
    name: SHELL
    env: yes
    job: /bin/zsh

- name: Setup cron for batt
  ansible.builtin.cron:
    name: Batt cron
    minute: "0,15,30,45"
    job: ". $HOME/.zshrc; batt cron"

- name: Setup cron for dfh
  ansible.builtin.cron:
    name: dfh cron
    minute: "0,15,30,45"
    job: ". $HOME/.zshrc; dfh cron"
