---
- name: Copy zshrc
  copy:
    src: zshrc
    dest: ~{{ macbook_user.stdout }}/.zshrc

- name: Create zsh directory
  file:
    path: "~{{ macbook_user.stdout }}/.zsh"
    state: directory

- name: Copy aliases
  copy:
    src: zsh/aliases
    dest: ~{{ macbook_user.stdout }}/.zsh/aliases

- name: Copy debian
  copy:
    src: zsh/debian
    dest: ~{{ macbook_user.stdout }}/.zsh/debian

- name: Copy git aliases
  copy:
    src: zsh/git
    dest: ~{{ macbook_user.stdout }}/.zsh/git

- name: Add debian to path.
  lineinfile:
    path: ~/.zsh/aliases
    line: source $HOME/.zsh/debian
    insertbefore: BOF

- name: Register ansible location
  become: false
  shell: command python3 -m site --user-base
  register: python_location

- name: Add ansible to path.
  lineinfile:
    path: ~/.zshrc
    line: export PATH="{{ python_location.stdout }}/bin:$PATH"

- name: collect server info
  shell: "curl -H 'User-Agent: keycdn-tools:https://google.com' 'https://tools.keycdn.com/geo.json?host={{ ansible_default_ipv4.address }}' > ~{{ macbook_user.stdout }}/provider.json"

- name: copy motd
  copy:
    src: motd
    dest: /etc/profile.d/motd.sh
  become: true
  become_user: root

- name: Add motd to path.
  lineinfile:
    path: ~/.zshrc
    line: sh /etc/profile.d/motd.sh

- name: register motd.sh exists
  stat:
    path: /etc/profile.d/motd.sh
  register: motd

- name: Conditionally Add motd to path.
  lineinfile:
    path: ~/.zshrc
    line: sh /etc/profile.d/motd.sh
  when: motd.stat.exists

- name: create empty tokens file only if one doesnt already exist
  copy:
    content: ""
    dest: ~{{ macbook_user.stdout }}/.zsh/tokens
    force: no

- name: create trial file for new aliases if one doesn't already exist
  copy:
    content: "tinker(){\n  echo try out new aliases here, not in main file\n}"
    dest: ~{{ macbook_user.stdout }}/.zsh/trialling
    force: no

- name: copy js help file
  copy:
    src: help.js
    dest: ~{{ macbook_user.stdout }}/.zsh/help.js

- name: register rbenv exists
  stat:
    path: ~{{ macbook_user.stdout }}/.rbenv/bin/rbenv
  register: rbenv

- name: Conditionally Copy zsh rails
  copy:
    src: zsh/rails
    dest: ~{{ macbook_user.stdout }}/.zsh/rails
  when: rbenv.stat.exists

- name: Conditionally Add rails to zshrc.
  lineinfile:
    path: ~/.zshrc
    line: source $HOME/.zsh/rails
  when: rbenv.stat.exists
