- name: Copy zshrc
  template:
    src: zshrc.j2
    dest: ~{{ macbook_user.stdout }}/.zshrc

- name: Create zsh directory
  file:
    path: "~{{ macbook_user.stdout }}/.zsh"
    state: directory

- name: Copy main aliases file
  copy:
    src: zsh/main
    dest: ~{{ macbook_user.stdout }}/.zsh/main

- name: configure terminal for mac
  import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- name: configure terminal for pi
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: include git
  import_tasks: git.yml

- name: Copy godaddy file
  copy:
    src: zsh/godaddy
    dest: ~{{ macbook_user.stdout }}/.zsh/godaddy

- name: Copy supabase file
  copy:
    src: zsh/supabase
    dest: ~{{ macbook_user.stdout }}/.zsh/supabase

- name: Copy macfair file (this machine)
  template:
    src: zsh/macfair
    dest: ~{{ macbook_user.stdout }}/.zsh/macfair
  when: hostvars['localhost']['hostname'].stdout == ansible_hostname

- name: Copy macfair file (other machines)
  copy:
    src: zsh/macfair
    dest:  ~{{ macbook_user.stdout }}/.zsh/macfair
  when: hostvars['localhost']['hostname'].stdout != ansible_hostname

- name: print role name
  set_fact:
    parent_role_name: "{{ role_name }}"

- name: add version
  include_role:
    name: version
