---
- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~{{ macbook_user.stdout }}/.oh-my-zsh

- name: Copy zshenv
  copy:
    src: zshenv
    dest: ~{{ macbook_user.stdout }}/.zshenv
    
- name: Copy zshrc
  copy:
    src: zshrc
    dest: ~{{ macbook_user.stdout }}/.zshrc

- name: Copy zfiles
  copy:
    src: zfiles
    dest: ~{{ macbook_user.stdout }}/zfiles

- name: Copy zsh theme
  copy:
    src: server/cerico.zsh-theme
    dest: ~{{ macbook_user.stdout }}/.oh-my-zsh/themes/cerico.zsh-theme

- name: change user shell to zsh 
  become: true
  become_user: root
  user:
    name: "{{ macbook_user.stdout }}"
    shell: /bin/zsh

- name: Add ansible to path.
  lineinfile:
    path: ~/.zshrc
    line: export PATH="$HOME/Library/Python/3.8/bin/:$PATH"

- name: source zshrc
  shell: source ~/.zshrc
