---
- name: get the username running the deploy
  become: false
  ansible.builtin.command: whoami
  register: macbook_user

- debug: var=macbook_user.stdout

- name: get git email
  become: false
  ansible.builtin.command: git config --get user.email
  register: git_email
  ignore_errors: true

- debug: var=git_email.stdout

- name: get git name
  become: false
  ansible.builtin.command: git config --get user.name
  register: git_name
  ignore_errors: true

- debug: var=git_name.stdout

- name: get the brew location
  become: false
  ansible.builtin.command: which brew
  register: brew_location
  when: ansible_os_family == "Darwin"

- debug: var=brew_location.stdout

- name: get the brew users name
  become: false
  ansible.builtin.command: stat -f "%Su" {{ brew_location.stdout }}
  register: brew_user
  when: ansible_os_family == "Darwin"

- debug: var=brew_user.stdout
  when: ansible_os_family == "Darwin"

- name: print role name
  set_fact:
    parent_role_name: "{{ role_name }}"

- name: add version
  include_role:
    name: version
