---
- name: get the username running the deploy
  become: false
  ansible.builtin.command: whoami
  register: macbook_user

- name: get the brew users name
  become: false
  ansible.builtin.command: stat -f "%Su" /usr/local/bin/brew
  register: brew_user
  when: ansible_os_family == "Darwin"
