---
- name: install homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - "homebrew/services"
    - "homebrew/cask"
  tags:
    - initialize

- name: install core packages
  homebrew:
    name: [
      "youtube-dl",
      "gh",
      "jq",
      "wget",
      "gcc",
      "openssl",
      "cmake",
      "git",
      "git-lfs",
      "moreutils",
      "findutils",
      "gnupg",
      "grep",
      "screen",
      "pigz",
      "tree",
      "shared-mime-info",
      "heroku",
    ]
    state: present
  tags:
    - initialize

- name: Set a hostname
  ansible.builtin.hostname:
    name: kelso

- name: Create wallpapers directory.
  file:
    path: "~{{ macbook_user.stdout }}/wallpapers"
    state: directory

- name: Copy wallpapers
  copy:
    src: "{{ item }}"
    dest: ~/wallpapers
  with_items:
  - wallpapers/bluetiled.png
  - wallpapers/greentiled.png
  - wallpapers/oaktiled.png

- name: wallpaper
  shell: osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/Users/{{ macbook_user.stdout }}/wallpapers/oaktiled.png"'
