---
- name: install homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - "homebrew/services"
    - "homebrew/cask"
    - "heroku/brew"
  tags:
    - initialize

- name: install core packages
  homebrew:
    name: [
      "youtube-dl",
      "jq",
      "wget",
      "gcc",
      "openssl",
      "cmake",
      "git",
      "git-lfs",
      "moreutils",
      "findutils",
      "gnupg",
      "grep",
      "screen",
      "pigz",
      "tree",
      "shared-mime-info",
      "heroku",
    ]
    state: present
  tags:
    - initialize

- name: Set a hostname
  ansible.builtin.hostname:
    name: kelso

- name: wallpaper
  shell: sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '~/Documents/b.jpg'" && killall Dock
