---
- name: install homebrew taps
  become: true
  become_user: "{{ brew_user.stdout }}"
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - "homebrew/services"
    - "homebrew/cask"

- name: install core packages
  become: true
  become_user: "{{ brew_user.stdout }}"
  homebrew:
    name: [
      "youtube-dl",
      "gh",
      "jq",
      "wget",
      "gcc",
      "openssl",
      "cmake",
      "git",
      "git-lfs",
      "moreutils",
      "findutils",
      "gnupg",
      "grep",
      "screen",
      "pigz",
      "tree",
      "ffmpeg",
      "shared-mime-info",
    ]
    state: present

- name: pip install jmespath
  shell: pip3 install jmespath

- name: Set a hostname
  ansible.builtin.hostname:
    name: kelso