---
- name: Clone Rbenv
  git: repo=git@github.com:picfair/fleetnation.git dest=~{{ macbook_user.stdout }}/fleetnation
  tags:
    - fleetnation

- name: copy makefile
  copy:
    src: Makefile
    dest: ~{{ macbook_user.stdout }}/fleetnation/
