---
- name: Create directory for installed apps
  file:
    path: "~{{ brew_user.stdout }}/Applications"
    state: directory
    mode: 0775

- name: install cask apps
  become: true
  become_user: "{{ brew_user.stdout }}"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - "hpedrorodrigues/tools/dockutil"
    - "vlc"
    - "firefox"
    - "alfred"
    - "iterm2"
    - "vagrant"
    - "vagrant-manager"
    - "tunnelblick"
    - "slack"
    - "visual-studio-code"
    - "brave-browser"
    - "google-chrome"
