export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="cerico-w-user"
ZSH_DISABLE_COMPFIX=true
plugins=(git)
echo -e "\033]50;SetProfile=coffee\a"

source $ZSH/oh-my-zsh.sh

source $HOME/.zshenv
source $HOME/.zsh/aliases

eval "$(rbenv init - zsh)"
