name: Docs
on:
  push:
    branches:
      - publish-docs

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: make a gitconfig
        run: |
          echo -e "[user]
            name = github-runner
            email = githubrunner@google.fi
          " > ~/.gitconfig

      - name: is gitconfig there
        run: cat ~/.gitconfig

      - name: installs the site
        run: npm_config_yes=true npx venlo@latest --default site documentation

      - name: empties template pages
        run: rm -rf site/src/pages/[a-z]*.astro

      - name: copies the Docs
        run: cp -r docs/*md site/src/content/docs

      - name: copies top level mds
        run: cp *md site/src/content/top

      - name: copies top readme to index
        run: cp README.md site/src/content/top/index.md

      - name: Build
        run: cd site && make build

      - name: Rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: site/dist/
          remote_path: "/var/www/html/macfair.io37.ch"
          remote_host: macfair.io37.ch
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
